"""Offline stub provider.

Deterministic, instant, costs nothing, needs no key — the whole app runs on it.
Use it for local UI work, for tests, and for demos.  It recognises the task
markers that ``core.prompts`` embeds (``[[SS:OUTLINE]]`` and friends) and
returns correctly shaped output for each.
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import re
from collections.abc import AsyncIterator, Sequence
from typing import Any

from syllabus_studio.config import Settings

from ..base import BaseProvider, Message, ModelTier
from ..registry import register

MARKER = re.compile(r"\[\[SS:([A-Z_]+)\]\]")


def _seed(text: str) -> int:
    return int(hashlib.sha256(text.encode()).hexdigest()[:8], 16)


def _topics(syllabus: str, n: int) -> list[str]:
    """Pull plausible topic phrases out of the pasted syllabus itself."""
    lines = [ln.strip(" \t-*0123456789.)") for ln in syllabus.splitlines()]
    cand = [ln for ln in lines if 12 <= len(ln) <= 80 and not ln.isupper()]
    if not cand:
        cand = ["Foundations", "Core methods", "Evaluation", "Applications", "Practice"]
    step = max(1, len(cand) // n)
    # Spread picks across the document, then wrap so short syllabi still fill n slots.
    return [cand[(i * step) % len(cand)][:70] for i in range(n)]


def _outline(prompt: str) -> dict[str, Any]:
    body = prompt.split("SYLLABUS:", 1)[-1]
    topics = _topics(body, 12)
    modules = []
    for mi in range(4):
        lessons = [
            {
                "title": topics[mi * 3 + li] if mi * 3 + li < len(topics) else f"Topic {mi}.{li}",
                "hook": "A concrete look at what this changes in practice.",
                "minutes": 10 + li,
            }
            for li in range(3)
        ]
        modules.append(
            {
                "title": f"Part {mi + 1}: {topics[mi] if mi < len(topics) else 'Further study'}",
                "summary": "Generated by the offline provider — set a real provider for real content.",
                "outcomes": ["Explain the core idea", "Apply it to your own material"],
                "lessons": lessons,
            }
        )
    return {
        "title": "Offline Sample Course",
        "subtitle": "built by the echo provider",
        "level": "intermediate",
        "skills": [
            "Run the app end to end without an API key",
            "See the full course shape before spending tokens",
            "Swap in a real provider when ready",
        ],
        "modules": modules,
    }


def _lesson(prompt: str) -> dict[str, Any]:
    m = re.search(r"LESSON TO WRITE: (.+)", prompt)
    title = m.group(1).strip() if m else "Untitled lesson"
    return {
        "bigIdea": (
            f"This is placeholder content for “{title}”, produced by the offline provider so the "
            "application runs with no API key. ==Set SS_LLM_PROVIDER=anthropic== to get the real thing."
        ),
        "sections": [
            {
                "heading": "How this works",
                "body": (
                    "Every lesson is written on demand by the configured provider and then stored, "
                    "so opening it again is free. ==The echo provider returns this fixed text.==\n\n"
                    "Point `SS_LLM_PROVIDER` at `anthropic` (or `ollama`) in your `.env`, restart, "
                    "and use **Rewrite this lesson** to replace this placeholder."
                ),
                "note": "Nothing here was generated from your syllabus — it is a fixed stub.",
            },
            {
                "heading": "What to check while offline",
                "body": (
                    "This mode is for working on the parts that do not need a model:\n\n"
                    "- navigation, progress tracking, and the completion ring\n"
                    "- quiz interaction and scoring\n"
                    "- flashcards built from key terms\n"
                    "- export and import of course bundles"
                ),
                "note": "",
            },
        ],
        "keyTerms": [
            {"term": "Provider", "definition": "The pluggable adapter that talks to a model."},
            {
                "term": "Tier",
                "definition": "quick / default / complex — mapped to a model per provider.",
            },
            {
                "term": "Bundle",
                "definition": "A portable JSON file holding a course and its lessons.",
            },
            {
                "term": "Store",
                "definition": "Where courses live: sqlite locally, or a remote instance.",
            },
        ],
        "worked": {
            "title": "Switching to a real provider",
            "steps": [
                "Copy .env.example to .env.",
                "Set ANTHROPIC_API_KEY to your key.",
                "Set SS_LLM_PROVIDER=anthropic.",
                "Restart the server.",
                "Open any lesson and press “Rewrite this lesson”.",
            ],
        },
        "quiz": [
            {
                "q": "Why does the offline provider exist?",
                "options": [
                    "To run the app and its tests without an API key",
                    "To cache real model output",
                    "To compress course bundles",
                    "To validate the syllabus format",
                ],
                "answer": 0,
                "why": (
                    "It returns fixed, correctly shaped content so the UI, storage and API can be "
                    "exercised for free. It does not cache anything — stored lessons do that."
                ),
            }
        ],
        "practice": [
            {
                "task": "Set a real provider in .env and regenerate this lesson.",
                "hint": "GET /api/v1/health reports which provider is live.",
            }
        ],
    }


def _faq(prompt: str) -> dict[str, list[dict[str, str]]]:
    m = re.search(r"LESSON: (.+)", prompt)
    title = m.group(1).strip() if m else "this lesson"
    return {
        "faq": [
            {
                "q": f"Is anything in “{title}” real, or is it all placeholder?",
                "a": "All placeholder. The **echo** provider writes fixed text so the app runs "
                "offline.",
            },
            {
                "q": "Why would a precomputed answer ever beat asking a live model?",
                "a": "A strong model wrote it at authoring time with the whole lesson in front of it, "
                "which a small local model at read time often cannot match.",
            },
            {
                "q": "What do I change to get real questions here?",
                "a": "Set `SS_AUTHOR_PROVIDER` (or `SS_LLM_PROVIDER`) to a real provider and re-run "
                "enrichment with force.",
            },
        ]
    }


@register("echo")
class EchoProvider(BaseProvider):
    """A provider that never leaves the machine."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def _reply(self, messages: Sequence[Message]) -> str:
        prompt = "\n\n".join(m.content for m in messages)
        found = MARKER.search(prompt)
        task = found.group(1) if found else ""
        if task == "OUTLINE":
            return json.dumps(_outline(prompt))
        if task == "LESSON":
            return json.dumps(_lesson(prompt))
        if task == "FAQ":
            return json.dumps(_faq(prompt))
        if task == "LENS":
            return (
                "**Offline provider.** A real answer would re-explain the lesson through the lens "
                "you picked.\n\n"
                "- the lens prompt reached the provider correctly\n"
                "- streaming is working, since you are reading this a chunk at a time\n"
                "- set `SS_LLM_PROVIDER=anthropic` for the real explanation"
            )
        last = messages[-1].content if messages else ""
        return (
            "**Offline provider.** Your question reached the tutor endpoint intact:\n\n> "
            + last.strip()[:300]
            + "\n\nSet a real provider in `.env` to get an actual answer."
        )

    async def complete(
        self,
        messages: Sequence[Message],
        *,
        tier: ModelTier = "default",
        max_tokens: int | None = None,
    ) -> str:
        await asyncio.sleep(0.05)
        return self._reply(messages)

    async def stream(
        self,
        messages: Sequence[Message],
        *,
        tier: ModelTier = "default",
        max_tokens: int | None = None,
    ) -> AsyncIterator[str]:
        text = self._reply(messages)
        for i in range(0, len(text), 24):
            await asyncio.sleep(0.02)
            yield text[i : i + 24]

    def describe(self) -> dict[str, Any]:
        return {"provider": self.name, "available": True, "offline": True}
